version: '3.7'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: 'tracing_api'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'tracing'
    ports:
      - '5432:5432'

  jaeger:
    container_name: 'jaeger'
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '16686:16686'
