name: LTS CD

on:
  push:
    branches: [ lts ]
  pull_request:
    branches: [ lts ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lts

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: Cache API Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/lts/*.gradle*') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        path: packages/lts
        username: ryanchristian4427
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ryanchristian4427/scrumble-lts
        tags: latest
