name: Node.js CI

on:
  push:
    branches: [ lts ]
  pull_request:
    branches: [ lts ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: /home/runner/.cache/yarn/v6
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          
    - run: cd packages/web-app
    - run: ls
    - name: Install Dependencies
      run: yarn
    - name: Build App
      run: yarn build

    - name: rsync deployments (Build)
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete
        path: build/*
        remote_path: /home/${{ secrets.DEPLOY_USER }}/scrumble/www/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
